			
// Copyright 2006-2016 ClickTale Ltd., US Patent Pending
// PID: 53068
// Generated on: 3/2/2016 6:36:06 AM (UTC 3/2/2016 12:36:06 PM)



function PCCmain(){document.location.href.indexOf("COSummary-Submit")>-1&&0==jQuery("#dwfrm_billing").length&&"function"==typeof ClickTaleEvent&&ClickTaleEvent("Checkout: Confirmation Page "),jQuery(".blk-nav--primary>li>a").hover(function(){var e=jQuery(".blk-nav--primary>li>a").index(this),i='jQuery(".blk-nav--primary>li>.level-2:eq('+e+')").css({"display":"block","width":"100%","left":"0","position":"absolute","padding-left":"173px"})';"function"==typeof ClickTaleExec&&ClickTaleExec(i)},function(){var e=jQuery(".blk-nav--primary>li>a").index(this),i='jQuery(".blk-nav--primary>li>.level-2:eq('+e+')").css({"display":"none","width":"0","padding-left":"0px"})';"function"==typeof ClickTaleExec&&ClickTaleExec(i)}),jQuery(".blk-nav--primary>li>.level-2").hover(function(){var e=jQuery(".blk-nav--primary>li>.level-2").index(this),i='jQuery(".blk-nav--primary>li>.level-2:eq('+e+')").css({"display":"block","width":"100%","left":"0","position":"absolute","padding-left":"173px"})';"function"==typeof ClickTaleExec&&ClickTaleExec(i)},function(){var e=jQuery(".blk-nav--primary>li>.level-2").index(this),i='jQuery(".blk-nav--primary>li>.level-2:eq('+e+')").css({"display":"none","width":"0","padding-left":"0px"})';"function"==typeof ClickTaleExec&&ClickTaleExec(i)}),jQuery("#pdpMain").is(":visible")&&"function"==typeof ClickTaleEvent&&ClickTaleEvent("Product Page"),jQuery(".search-show").click(function(){"function"==typeof ClickTaleEvent&&ClickTaleEvent("Search Clicked")}),jQuery("#dwfrm_login").length>0&&"function"==typeof ClickTaleEvent&&ClickTaleEvent("Checkout: Step1: Login"),jQuery("#dwfrm_singleshipping_shippingAddress").length>0&&"function"==typeof ClickTaleEvent&&ClickTaleEvent("Checkout: Step2: Shipping"),jQuery("#dwfrm_billing").length>0&&"function"==typeof ClickTaleEvent&&ClickTaleEvent("Checkout: Step3: Billing"),jQuery(".co-summary").length>0&&("function"==typeof ClickTaleEvent&&ClickTaleEvent("Checkout: Step4: Place Order"),jQuery(".button-fancy-large").click(function(){"function"==typeof ClickTaleEvent&&ClickTaleEvent("Checkout: Step4: Place Order: Place Order Clicked")}))}window.ctlib={},ctlib.doOnlyWhen=function(e,i,n,l,t){return e&&i?("undefined"==typeof n&&(n=1e3),"undefined"==typeof l&&(l=20),--l<0?void("function"==typeof t&&t()):i()?void e():void setTimeout(function(){ctlib.doOnlyWhen(e,i,n,l,t)},n)):void 0},ctlib.doOnlyWhen(PCCmain,function(){return window.jQuery&&"function"==typeof jQuery.fn.on&&"function"==typeof jQuery.fn.one&&"function"==typeof ClickTaleIsRecording&&ClickTaleIsRecording()?!0:!1},250,40);

